### PR TITLE
fixed nextRunAt reports latest time and not earliest

### PR DESCRIPTION
**Pull request by sblcook**

### CODE REVIEW

**Comment by ajvb** [comment]
Hey @sblcook, thanks for the PR. There currently is an inprogress PR that has been dead for about 11 days - https://github.com/ajvb/kala/pull/159

If you can add a regression test I'd happily merge this today.

**Comment by sblcook** [comment]
Ah ok I see that now. I will try to add a regression test, but I have never actually done regression testing.

**Comment by ajvb** [comment]
Read the PR I linked to, what is needed is laid out in it. Feel free to drop any questions you have in here.

**Comment by gwoo** [comment]
Duplicate of #146. Superseded by #174.

**Pull request closed without merging**
