### PR TITLE
Fix stat for NextRunAt time (#146)

### LINKED ISSUE #146: NextRunAt - reports latest time not earliest
the logic for determining next run time for a set of jobs is reversed and thus reports the latest run at time for the set

		if nextRun.IsZero() {
			nextRun = jobs.NextRunAt
		//} else if (nextRun.UnixNano() - jobs.NextRunAt.UnixNano()) < 0 {
		} else if (nextRun.UnixNano() - jobs.NextRunAt.UnixNano()) > 0 {
			nextRun = jobs.NextRunAt // we want earliest not latest
		}

simple fix to reverse the test ( > 0)

### PR DESCRIPTION
**Pull request by rjsabatini**
Fix #146 to have NextRunAt report the earliest time instead of latest.

### CODE REVIEW

**Comment by ajvb** [comment]
@rjsabatini Would you mind including a regression test along side this change?

**Comment by rjsabatini** [comment]
@ajvb I'm extremely new to Go, and particularly testing in go. I've been doing some research and could use a bit of guidance. Would this be a another `assert` in the `stats_test.go`, or a new test function?

**Comment by rjsabatini** [comment]
@ajvb I made an attempt at the regression test. Let me know if isn't what you were expecting, and I'll be happy to make another attempt.

**Comment by ajvb** [comment]
@rjsabatini This is really close! What I'd suggest is making a job with a much shorter schedule (can use `GetMockJobWithSchedule`) and make sure that it's NextRunAt time is the same as what is returned by `NewKalaStats`. Does that make sense?

**Pull request merged**
