### PR TITLE
config file implementation

### PR DESCRIPTION
**Pull request by cescoferraro**
- Switched from codegangster/cli to spf13/cobra and spf13/viper.
- Remove deprecated Godep/_workspaces folder in favor to vendor/ folder.
- Added gulpfile to faster golang environment

### CODE REVIEW

**Comment by cescoferraro** [comment]
Solves #89

**Comment by cescoferraro** [comment]
Circle has some godep issues. I suck at Godeps. Have you considered using glide?

**Comment by cescoferraro** [comment]
`package github.com/ajvb/kala/vendor/github.com/garyburd/redigo/redis
	imports github.com/garyburd/redigo/internal: use of internal package not allowed
package github.com/ajvb/kala/vendor/golang.org/x/crypto/ed25519
	imports golang.org/x/crypto/ed25519/internal/edwards25519: use of internal package not allowed`.

Some packages fail with Godep and go1.4 and 1.5 with the same issue.  [Like this one!](https://github.com/prasmussen/gdrive/issues/81). As the issue suggests, CI should be running go1.6, which we are not (1.5.3). [Many people](https://discuss.circleci.com/t/switch-to-golang-1-6-for-builds/2608/2) using Circle have had the need to update go version for the same reason.  But I suppose @ajvb is the only one that can do this.

**Comment by elimisteve** [comment]
@ajvb FYI:

> Remove deprecated Godep/_workspaces folder in favor to vendor/ folder.

`Godep/_workspaces` is actually compatible with older versions of Go (pre-1.5), unlike the newer `vendor/` directory, I believe.

**Comment by cescoferraro** [comment]
From the [original](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit) Go 1.5 Vendor Experiment paper.

> If we decide that the vendor behavior is correct, then in a later release (possibly Go 1.6) we would make the vendor behavior default on. Projects containing “vendor” directories could still use “GO15VENDOREXPERIMENT=0” to get the old behavior while they convert their code. In a still later release (possibly Go 1.7) we would remove the use of the environment variable, locking in the vendoring semantics.

**Comment by ajvb** [comment]
@cescoferraro I'm more than happy to review this, but I would not like to move away from Godeps and CLI libraries at the same time. Also, I'd like to ask you to get tests passing before I start reviewing.

**Comment by cescoferraro** [comment]
@ajvb Hey! In order to use the new packages, I need the new dependencies. Godeps works just fine on my machine, but it fails on Circle, because of some Godeps bug on another packages kala uses[github.com/garyburd/redigo/redis / golang.org/x/crypto ]. I am king of locked here. BTW, i am not moving away from Godeps, I am just using the new vendoring semantics.  I can submit a new PR, switching to glide. Or you can change the golang version on the CI. Or whatever you like better. Its up to you on how you want me to tackle this.

**Comment by gwoo** [comment]
I agree cobra and viper are nice libraries and would be interesting to move in that direction. It's very hard to see the appropriate changes because they seem to be wrapped up in the godeps -> vendor changes. If you could base changes off the `dev` branch (#157) then we might be able get them in here.

**Comment by tooolbox** [comment]
@cescoferraro I know this was 3 years ago, but this library is now using Go Modules and it may be a little easier to make this change if you still desire.

**Pull request closed without merging**
